### ISSUE TITLE
How to determine the moon phase like 🌑🌒🌓🌔🌕🌖🌗🌘 ?

### ISSUE THREAD

**Issue by gongzhang** [onekiloparsec/SwiftAA#105]
I'm still not quite sure how I should get the moon phase after reading https://github.com/onekiloparsec/SwiftAA/issues/63. 😂

The goal is to determine the current moon phase like: 🌑 🌒 🌓 🌔 🌕 🌖 🌗 🌘 . As I understand it, I need both `Moon.phaseAngle` and `Moon.positionAngleOfTheBrightLimb` information to draw the icon.

```
   phaseAngle  positionAngleOfTheBrightLimb

🌑   180°        ~ 260°
🌒   135           .
🌓   90°           .
🌔   45          ~ 290°
🌕   0           ~ 90°
🌖   45            .
🌗   90°           .
🌘   135           .
🌑   180°        ~ 80°
```

The `Moon.phaseAngle` is straightforward. However, how should I determine whether the left or right side of the moon is bright based on `Moon.positionAngleOfTheBrightLimb`? Also, this seems to assume that we all observe the moon from the northern hemisphere. Am I right?

**Comment by HerrAlien** [comment]
I'd use  selenographicPositionOfTheSun() instead of
positionAngleOfTheBrightLimb () , and examine the longitude.

Regards,
Alex

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by gongzhang** [comment]
@HerrAlien Thanks! 👍
