### ISSUE TITLE
Pluto

### ISSUE THREAD

**Issue by cmaldonado80** [onekiloparsec/SwiftAA#86]
Pluto: Astronomers took  it out from being a planet, but very important for astrology. I haven't found a way in SwiftAA to see in what degree it is located. I use 
the "apparentEclipticCoordinates" to see in what degree are the planets, but not available for Pluto or Dwarf Planet. Im I looking in the wrong place or its simply not available?

**Comment by cmaldonado80** [comment]
Correction im looking for the "ApparentGeocentricLongitude" of pluto

**Comment by onekiloparsec** [comment]
Hm... your question point to a tricky inconsistency between the various enums. Indeed, one should be able to get `ApparentGeocentricLongitude` from AA+ too. Investigating...

**Comment by onekiloparsec** [comment]
I am updating the code to make sure that the `Pluto` class, because it inherits from the `DwarfPlanet`  class, is able to correctly compute the `ApparentGeocentricLongitude` as part of the planetary details. 

It was somehow the case already, but the truncated enum prevented to achieve the complete the result, since it was routed to "undefined" Planetary Object.

**Comment by onekiloparsec** [comment]
I don't have tests however that would validate the computation. But what the new code is doing is simply giving access to the existing computations made by AA+.

**Comment by onekiloparsec** [comment]
SwiftAA 2.2.0 now released.
