### ISSUE TITLE
Failed to build for SwiftUI preview

### ISSUE THREAD

**Issue by Saturnyn** [onekiloparsec/SwiftAA#88]
Hello,

when I add the SwiftAA lib to my SwiftUI app, the live canvas preview fails to build:

`symbol(s) not found for architecture x86_64`

Here is the full error log:
[build-error-swift-UI.txt](https://github.com/onekiloparsec/SwiftAA/files/4140257/build-error-swift-UI.txt)

From what I understand, it looks like the ObjcAA framework is not built for x86_64 which the SwiftUI  preview  uses.

Did anyone run into the same problem ?
Since I am new to iOS development and struggled to just get the lib to work in a normal build, it is quite possible that I misconfigured something, so any advice would be appreciated :)

Thanks

Edit: forgot to mention the lib was added in Xcode via the Swift Package Manager (full disclosure: tried with Carthage but got another kind of error at runtime)

**Comment by onekiloparsec** [comment]
Hi. I struggled quite a lot to make the project work with all packaging managers. But I haven't tried to setup a SwiftUI setup (simply because I had no real time to try it). But I'll try!

**Comment by onekiloparsec** [comment]
I've made some progresses. There were 2 problems: 
- it seems that standard Objective-C exception cannot be used inside ObjC++ modules, and I've thus replaced them with standard C++ ones.
- There was a forbidden "+" character in the AA+ bundle name. I changed the "AA+" package lib to "AAplus".

Could you give a try and let me know you have a new error ? (something related to NSObject)?

- Choose "master" branch in your SwiftAA package dependency in your project (instead of a fixed version range)
- Make sure to refresh to the latest version
- Remove the "AA+" lib dependency in the "Framrworks, Libraries and Embedded Content" section of your project settings (it doesn't exist anymore)
- Manually add the new "AAplus" in place.

**Comment by onekiloparsec** [comment]
Hm, there is something I don't get. When adding only SwiftAA as dependency of my SwiftUI project, everything compiles fine and it runs on simulator. The problem occurs only when one includes ObjCAA. Please, could you try by specifying only SwiftAA and see how it goes ? (it seems to work both with master branch and existing 2.2.2 release).

<img width="598" alt="Screenshot 2020-02-01 at 10 56 06" src="https://user-images.githubusercontent.com/226224/73590323-7afdb880-44e1-11ea-8079-b0a93c8c242c.png">

**Comment by Saturnyn** [comment]
Hi,
thanks for following up on this.

When I used Swift Package Manager to add SwiftAA, I only selected "SwiftAA", so it is already the only one I have in my Framework list (the project does compile and run fine like this, my only problem is with the SwiftUI preview).

I tried switching to the master branch and tried with and without "AAplus". I got the same error in the preview in both cases. The error log did change a little compared to what I had previously so I'm sending the new one: [build-error-swift-UI-2.txt](https://github.com/onekiloparsec/SwiftAA/files/4147298/build-error-swift-UI-2.txt)


Just to make sure we are trying the same thing,  the preview I have a problem with is activated like this:

![Screenshot 2020-02-03 at 11 19 17](https://user-images.githubusercontent.com/1634171/73645160-0f4d5400-4677-11ea-8bfc-d70475001cfd.png)

And the error looks like this:
![Screenshot 2020-02-03 at 11 07 20](https://user-images.githubusercontent.com/1634171/73644295-62260c00-4675-11ea-9c60-fc91c1981499.png)

I think it is a fairly recent addition to XCode and it requires macOS Catalina to run, so maybe we do not get the same result because we are on different versions of XCode ? I am using the latest I think (Version 11.3.1 (11C504))

**Comment by onekiloparsec** [comment]
Wonderful, with screenshots. Will check as soon as I can (very busy during the week). I'm also on Catalina.

**Comment by sbenitezb** [comment]
I’m experiencing the same issue. For some reason Xcode is unable to link against a dynamic library with objc runtime when previewing SwiftUI views. Makes working with SwiftUI difficult because one of the premises of SwiftUI is you write code which you can instantly preview without running your app.

Setting the ObjCAA product’s type to .static solves the issue. As SwiftAA is being statically linked with both ObjCAA and AAplus for whatever reason even when both libraries are set dynamic, then this setting doesn’t change the resulting product.

**Comment by onekiloparsec** [comment]
Really sorry for having let the time flew on this issue... Just overwhelmed with day job. Would you mind making a PR ? I'd be happy to merge rapidly.

**Comment by sbenitezb** [comment]
Sure, no problem. I’m still baffled it’s not building all libraries as dynamic as it should. I would prefer no to link SwiftAA dependencies statically, so I’ll keep looking for a better solution to solve the issue. If I don’t find one, I’ll make a PR.

**Comment by onekiloparsec** [comment]
v2.2.5 available. @sbenitezb @Saturnyn If you build something with SwiftAA, I'd be happy to include it in the list of apps using it in the README.
