### ISSUE TITLE
Getting coordinates of stars

### ISSUE THREAD

**Issue by jjfster** [onekiloparsec/SwiftAA#91]
Can I use this library to get positions of the brightest stars (Regulus, etc.)?  If so, how would I get started?

**Comment by onekiloparsec** [comment]
Positions of brightest stars do not change with time (apart from a very smal fraction that has a significant proper motion – but even then, displacement is small). Hence coordinates of brightest stars are basically fixed numbers (for a given epoch). Hence SwiftAA will be of no help here.

I can recommend many places to look for, but I'll starty with mine:

https://www.arcsecond.io/objects to look for objects information.

https://www.arcsecond.io/iobserve (to actually prepare observations depending on date, position etc...)

If you are willing to script things or make APIs request, I'd suggest to use our APIs: https://api.arcsecond.io (also available through a Python CI/module).

**Comment by jjfster** [comment]
Thanks for the quick response.

I'll dig around.  I was actually looking for an easy way to get the position in terms of the current azimuth and elevation.

**Comment by onekiloparsec** [comment]
I am doing these kind of software since more than 10 years now. I think your best bet is iObserve on the web https://www.arcsecond.io/iobserve  :-) 

You'll get easy access to any object (or manual ones) you import, with precise altitude, tracking and position at any moment during the night.

You can see a detailed screenshot on the front page of arcsecond.io
